### PR TITLE
feat: added support for className to <AnchoredOverlay>

### LINKED ISSUE #4739: Add support for `className` to `<AnchoredOverlay>`
At present, `<AnchoredOverlay>` can't be assigned classes. This means that styling can't be applied to the associated overlay.

In our case, we needed to adjust its z-index, for example.

### PR DESCRIPTION
**Pull request by Princeyadav05**
Closes #4739 

This PR adds the ability to apply custom CSS classes to the `AnchoredOverlay` component's overlay. 

#### Changed

- Updated the `AnchoredOverlay` component to pass through all `overlayProps` to the internal `Overlay` component.

#### Removed

- N/A

### Rollout strategy

- [ ] Minor release
- [x] Patch release
- [ ] Major release; if selected, include a written rollout or migration plan
- [ ] None; if selected, include a brief description as to why

This change adds new functionality without breaking existing behavior, making it suitable for a minor release.

### Testing & Reviewing

To test this change:

1. Use the `AnchoredOverlay` component with a custom class:
   ```jsx
   <AnchoredOverlay
     overlayProps={{
       className: "my-custom-overlay-class"
     }}
     // ... other props
   >
     {/* Overlay content */}
   </AnchoredOverlay>
   ```

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Storybook)
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge
- [ ] (GitHub staff only) Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

### CODE REVIEW

**Review by broccolinisoup — CHANGES_REQUESTED** [review]
Hello! Thanks for pushing this PR. There is a type error about the new `className` prop. Could you please make sure the new prop type is also defined?

**Comment by Princeyadav05** [comment]
> Hello! Thanks for pushing this PR. There is a type error about the new `className` prop. Could you please make sure the new prop type is also defined?

Sure, will look at it today.

**Comment by broccolinisoup** [comment]
Hello @Princeyadav05 👋🏻 Let me know if you need a hand with fixing the type issue!

We have another PR raised for the same issue and I am trying to coordinate so that we can have both of your contributions, ideally 😊

**Comment by Princeyadav05** [comment]
> Hello @Princeyadav05 👋🏻 Let me know if you need a hand with fixing the type issue!
> 
> We have another PR raised for the same issue and I am trying to coordinate so that we can have both of your contributions, ideally 😊

Will try to close it in a couple of hours. Thanks you for your co-ordination. 😊

**Comment by Princeyadav05** [comment]
@broccolinisoup  have made the required changes. Do let me know if anything else is required.

**Review by broccolinisoup — APPROVED** [review]
Thanks @Princeyadav05!! 🎉

**Pull request merged**
