### PR TITLE
docs(versioning): update docs to include landmark roles

### PR DESCRIPTION
**Pull request by joshblack**
Add a section to our versioning docs to include landmark roles as they relate to semver.

## Feedback

Would love to hear what you all think about this section and if it accurately captures our semver policy 👀 Let me know if there is anything missing or anything that needs to be changed!

### CODE REVIEW

**Review by broccolinisoup — APPROVED** [review]
I love this 🔥 My only feedback/question is that should we elaborate what we mean by "potentially major" under the semver section? 👀

**Review by TylerJDev — APPROVED** [review]
Looks great! ✨

Off-topic, but it might be worth a discussion in the future to see if we should steer clear from having default landmarks all together in components and always give that choice to the consumer? This doesn't seem to be the norm in newer components, but I do see the friction that could be caused through updates such as with `PageLayout` and others. I really like the approach done in the fix https://github.com/primer/react/pull/3737 and I wonder if it could be applied elsewhere 🤔

**Review by iansan5653 — APPROVED** [review]
Awesome, thank you!

**Comment by joshblack** [comment]
@TylerJDev totally agreed, I think you're dead-on that we probably shouldn't be baking in default landmark roles. Let me see where would a good place be to capture that so that we consider it in future component work 👀 (or let me know if you have any places in mind where it may be good to capture this!)

**Pull request merged**
