### PR TITLE
refactor(project): update structure to monorepo

### PR DESCRIPTION
**Pull request by joshblack**
RFC: https://github.com/github/primer/discussions/2955

This Pull Request is a proposal to demonstrate the project structure for the RFC for moving Primer React to a monorepo.

### Checklist

- [x] Structure
  - [x] `@primer/react` added as workspace
  - [x] `docs` added as workspace
  - [x] `examples` added as workspaces
- [x] Tooling
  - [x] ESLint
  - [x] TypeScript
  - [x] Prettier
  - [x] Markdownlint
  - [x] Jest
  - [x] Changesets
- [x] GitHub Actions
  - [x] Deploy Production
  - [x] Deploy Preview
  - [x] Deploy Preview forks
  - [x] Release
  - [x] Release Canary
  - [x] Release Candidate
  - [x] Size
  - [x] CI
  - [x] Update Snapshots
  - [x] VRT
  - [x] Consumer Test

### Notes

- Due to `docs`, we need to have `--legacy-peer-deps` turned on by default
- Lack of hoisting options makes this process challenging 😅 it'd be great to use pnpm or `yarn` (specifically yarn v2+, not yarn v1)
  - For example, if we have a shared dependency (like mdx) that uses context then we require the package version to be the same across the monorepo (otherwise the contexts would be different and would not work)
- We could update our release canary step to only publish if a changeset is available in any package instead of forcing an individual package

### Known issues

- [x] ~~The styles for docs seems to be off 🤔~~

### Possible next steps

- Add documentation for common monorepo tasks
- Add more examples to the `examples` directory, in particular one for Next.js app router
- Refactor ad-hoc scripts under `script` to dedicated (internal) packages
- Add a "primer cli" that wraps common commands in the monorepo, in particular scaffolding different file types
- Explore alternate npm clients (such as pnpm, yarn) to help with dependency hoisting issues
- Explore monorepo tooling (such as nx, turbo, lerna) to help with common monorepo tasks

### CODE REVIEW

**Comment by joshblack** [comment]
cc @primer/react-reviewers let me know what you think when you have a sec! Finally got this PR in a good place where everything matches up to the RFC (barring some minor changes)

Would love to know what you all think about this structure and hear feedback from you on anything that comes to mind (including why are we doing this)

**Review by siddharthkp — APPROVED** [review]
I don't have enough knowledge to give feedback here, but happy to go forward with it from my side!

**Review by broccolinisoup — APPROVED** [review]
I don't have much experience/knowledge in monorepos but I fetched the branch and everything seems to be working golden ⭐ And loved the potential next steps ✨ 

I am happy to go with this change and excited to learn and explore more about it as we go 🙌🏻

**Comment by smockle** [comment]
Heads-up: This broke the “primer-react” workflow in code-stats-collector—the [past 18 hours of workflow runs](https://github.com/github/code-stats-collector/actions/workflows/primer-react.yml) have failed. I opened https://github.com/github/code-stats-collector/pull/672 to fix the issue by updating the paths in the workflow.

**Pull request merged**
