### PR TITLE
Update docs to match new major release breaking changes

### PR DESCRIPTION
**Pull request by SferaDev**
Requires:
- https://github.com/primer/eslint-plugin-primer-react/pull/21

Changes:
- Use new rule on md/mdx code snippets
- Update docs with new rule changes and minor prettier updates

### Screenshots

Please provide before/after screenshots for any visual changes

### Merge checklist

- [ ] Added/updated tests
- [x] Added/updated documentation
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by SferaDev** [comment]
I noticed this for ``StyledOcticon`` but actually there're lots of outdated examples after https://github.com/primer/react/pull/1639

**Review by siddharthkp — APPROVED** [review]
Yes! Love to see it

**Comment by SferaDev** [comment]
@siddharthkp Not sure if other props should be migrated, and/or if there's a linter rule to warn about this breaking change for the next major

**Comment by siddharthkp** [comment]
@SferaDev [eslint-plugin-primer-react](https://github.com/primer/eslint-plugin-primer-react) has a new release to go with the major version: https://github.com/primer/eslint-plugin-primer-react/releases

**Review by colebemis — APPROVED** [review]
Thank you ✨

**Comment by SferaDev** [comment]
It was bugging me that some props like ``mr`` should also be detected by the eslint plugin and are not. It seems that the ``pick`` method from [styled-system](https://github.com/styled-system/styled-system/blob/master/packages/props/src/index.js) does not have all props.

**Comment by SferaDev** [comment]
Created https://github.com/primer/eslint-plugin-primer-react/pull/21 to allow the rule to be executed on the code snippets from ``docs`` folder.

cc: @jfuchs

**Comment by mperrotti** [comment]
@SferaDev - could we get the conflicts resolved so we can merge this?

**Comment by SferaDev** [comment]
Sure thing, will update tomorrow

**Comment by SferaDev** [comment]
> @SferaDev - could we get the conflicts resolved so we can merge this?

Done! @mperrotti, however keep in mind that it requires https://github.com/primer/eslint-plugin-primer-react/pull/21

Actually this PR is nothing else than running ``lint --fix`` and ``prettier`` with that fix to the eslint plugin

**Pull request closed without merging**
