### PR TITLE
refactor: inline react-polymorphic

### LINKED ISSUE #2256: [RFE] stop consuming '@radix-ui/react-polymorphic' as it is deprecated upstream
Hey all, 

per https://github.com/radix-ui/primitives/pull/835 which went _live_ in [September 7, 2021](https://www.radix-ui.com/docs/primitives/overview/releases#september-7-2021) use of `@radix-ui/react-polymorphic'` become deprecated, with the new prefered syntax being described [here](https://www.radix-ui.com/docs/primitives/overview/styling#changing-the-rendered-element). 

Finally, early this year, the whole `@radix-ui/react-polymorphic` package was sunsetted per https://github.com/radix-ui/primitives/pull/1331. 

This is relevant because `@prime/react` is now supposed to properly behave over **react-18** and the latest  shipping  `@radix-ui/react-polymorphic` being consumed isn't _exactly_ aware of it...  the noise bellow is what what made me dig a bit on this...

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @radix-ui/react-polymorphic@0.0.14
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   99 more (@clerk/clerk-react, @primer/octicons-react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8 || ^17.0" from @radix-ui/react-polymorphic@0.0.14
npm WARN node_modules/@radix-ui/react-polymorphic
npm WARN   @radix-ui/react-polymorphic@"^0.0.14" from @primer/react@35.7.0
npm WARN   node_modules/@primer/react
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8 || ^17.0" from @radix-ui/react-polymorphic@0.0.14
npm WARN   node_modules/@radix-ui/react-polymorphic
npm WARN     @radix-ui/react-polymorphic@"^0.0.14" from @primer/react@35.7.0
npm WARN     node_modules/@primer/react
```

So, in the name of keeping things clean, and up to date it may make sense, IMHO, to keep with the times

All the Best, (and keep the great work!)

António

### PR DESCRIPTION
**Pull request by joshblack**
Closes #2256

This PR addresses #2256 by removing the `@radix-ui/react-polymorphic` dependency and inlining it within the project. It updates all imports from `@radix-ui/react-polymorphic` to the new internal file.

### CODE REVIEW

**Comment by joshblack** [comment]
Note to reviewers: it seems like CI failed on the `lint` stage. Should I go through and address the violations or would it make sense to ignore this file since we're inlining it from a package we were using? I wasn't sure what the side-effects would be of changing the types to meet the linter would be and wanted to double-check 👀

**Review by colebemis — APPROVED** [review]
I like this approach 👍 Should we put this in the `utils/` directory instead?

**Comment by colebemis** [comment]
> Note to reviewers: it seems like CI failed on the lint stage. Should I go through and address the violations or would it make sense to ignore this file since we're inlining it from a package we were using?

I think it's reasonable to disabling eslint for this file since it's copy and pasted

**Comment by joshblack** [comment]
@colebemis sounds good! Done 👍

**Pull request merged**
