### PR TITLE
Add tests generated by script

### PR DESCRIPTION
**Pull request by owenniblock**
Related to https://github.com/github/primer/issues/3043

While generating tests for my work on TabPanels, I noticed that it also generated tests for Dialog v1. It also now generates tests for Tooltip V2. Maybe this is a mistake and these versioned components should be changed, in the meantime I'm creating the tests in a separate PR so I can rebase and simplify my own PR.

If we should do something else, let me know :-)

### Rollout strategy

- [ ] Patch release
- [ ] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan
- [x] None; if selected, include a brief description as to why

Test changes only.

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Storybook)
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge
- [ ] (GitHub staff only) Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

### CODE REVIEW

**Review by keithamus — APPROVED** [review]

**Comment by joshblack** [comment]
@owenniblock I bet something is going on with the name in the generation script 🤔 It seems like we have a Dialogv1 and TooltipV2 file in the folder but in the script itself we have `Dialog v1` and `Tooltip V2`

Maybe as a convention we could update them in the generation script to be `DialogV1` and `TooltipV2`? And then remove the older file names, where applicable.

**Review by broccolinisoup — COMMENTED** [review]
Yeah totally agree with @joshblack - sorry it caused issues 😢

We have Tooltip snapshots added in this PR so they are not needed : https://github.com/primer/react/pull/4250/files

**Comment by owenniblock** [comment]
No need to apologise @broccolinisoup - I'm just trying to be a good citizen and add things if they're missing.

I'm still not 100% sure what I should be doing about the Dialog one, but I'll try and work that out today!

**Comment by owenniblock** [comment]
OK, going to close this and reopen a PR without the Tooltip stuff, thanks all 🙏

**Comment by owenniblock** [comment]
[replacement PR to rename the generation names](https://github.com/primer/react/pull/4319)

**Pull request closed without merging**
