### PR TITLE
Upgrade primitives and update snapshots

### PR DESCRIPTION
**Pull request by mperrotti**

### CODE REVIEW

**Comment by siddharthkp** [comment]
❗ package-lock seems to have switched back to version: 1

**Comment by mperrotti** [comment]
> package-lock seems to have switched back to version: 1

@siddharthkp - Do you mean `35.1.0`?  What would you expect it to be? I don't want this PR to trigger a new release.

**Comment by siddharthkp** [comment]
Nah, I mean this file

image

**Comment by siddharthkp** [comment]
CI decided not to run?? 🤔

**Comment by mperrotti** [comment]
Yea, I'm trying to figure out how to get it to re-run without pushing a garbage commit

**Review by siddharthkp — APPROVED** [review]
Yes! Looks great!

**Review by langermank — APPROVED** [review]

**Comment by siddharthkp** [comment]
Ouch! sorry for the failed check!

I approved Visual testing on this PR because we talked about it in the last engineering sync and it felt like the perfect PR that could use it. We don't have to fix it in this PR, feel free to ignore it for now until we have green starting point!

**Comment by mperrotti** [comment]
Closing because we merged another PR that upgrades `@primer/primitives`

**Pull request closed without merging**
