### PR TITLE
AnchoredOverlay + useAnchoredPosition: close overlay when menu goes out of view 

### PR DESCRIPTION
**Pull request by siddharthkp**
#### Changes

1. Adds an optional argument to `useAnchoredPosition` to observe changes to anchor element: `observe`
2. AnchoredPosition now uses  useAnchoredPosition with `observe` which means overlay re-positions based on changes to anchor's position (scroll, resize, etc)
3. AnchoredOverlay closes when anchor goes out of view (includes ActionMenu and SelectPanel, but not Autocomplete)

- Fixes https://github.com/primer/react/issues/2184

video:

https://user-images.githubusercontent.com/1863771/187722377-b98399fd-61ce-4065-b061-207e0674e5cf.mov

#### Notes for reviewer: 

1. Have kept the change in primer/react and not upstreamed to primer/behaviours because I'm not sure about the long term tradeoffs yet.
2. Using [reach/observe-rect](https://github.com/reach/observe-rect) which calls getBoundingRect on every requestAnimationFrame. Added 2 performance optimisations: 
  2.1 Observer is only initiated when overlay is open
  2.2 Callback is debounced (16ms) to make sure we're not updating state too fast
3. Considered alternate approach of adding scroll listeners on every parent up the tree, but decided against it because it attaches events on application elements

Checklist:
- [x] Check if new dependency works across build systems (library has support for [cjs, esm and umd](https://unpkg.com/browse/@reach/observe-rect@1.2.0/dist/))
- [ ] Is [this an okay way to load lodash](https://github.com/primer/react/pull/2200/files#diff-b302f9f2813f17720fbfab313cac4c110b2929452f2ecc1091d78d30e04d5f1bR3)?
- [ ] Check if there is a performance regression because of observer (using debounce but need to test with memex)
- [ ] Check if this approach is accessible (a11y discussion on [slack for github staff](https://github.slack.com/archives/C0FSWLQ0Y/p1661954660218019))
- [ ] Check if the type changes make sense for OnCloseGesture (maybe remove them from this PR)
- [ ] Check if Autocomplete should also add observe with useAnchoredPosition

### CODE REVIEW

**Comment by owenniblock** [comment]
[Slack discussion around the SelectPanel functionality here](https://github.slack.com/archives/C0FSWLQ0Y/p1661954660218019)

**Comment by inkblotty** [comment]
👋 Hi @siddharthkp - Would you cc @primer/accessibility-reviewers when this is out of Draft? 🙏

**Comment by siddharthkp** [comment]
cc @primer/accessibility-reviewers for review :)

**Comment by smockle** [comment]
> cc @primer/accessibility-reviewers for review :)

Caption: Screen recording of an open menu closing after its associated cell bounces back into view post-scrolling:
https://user-images.githubusercontent.com/3104489/189673468-5aec1f77-cec5-40a9-9cee-e4d9466040c0.mov

**Comment by smockle** [comment]
Other menus on github.com remain open as the page is scrolled, even if they are scrolled out of view. Here is the issue comment menu, for example:

Caption: Screen recording showing that the issue comment three-dot menu remains open even after it scrolls out-of-view:

https://user-images.githubusercontent.com/3104489/189692010-67f98bba-4f1f-473c-9099-8ae086eb3aaa.mov

**Comment by siddharthkp** [comment]
> Other menus on github.com remain open as the page is scrolled, even if they are scrolled out of view. Here is the issue comment menu, for example (screen recording below). I’d expect all menus to behave consistently.

Yes! that was my concern as well. The suggestion to close it came after my first iteration where it stays open:

Description: There is a sticky header above the table so the select panel awkwardly floats on when the table cell is "tucked under" the header. 

https://user-images.githubusercontent.com/1863771/189927290-f14caf6b-46dc-4983-8501-ddd7a888f28d.mov

(in the video, ignore the select panel jumping around, that's not the recommendation)

**Comment by lesliecdubs** [comment]
👋🏻 @siddharthkp just doing some triage on the PRC board and this one has been in "ready for review" for a while. Is this still active?

**Comment by siddharthkp** [comment]
> Is this still active?

We still need it 😅 but I haven't touched this in few weeks since the a11y feedback

**Pull request closed without merging**
