### PR TITLE
Fix type errors in next-major

### PR DESCRIPTION
**Pull request by mperrotti**
Fixes type errors we started getting recently in branches off of `next-major`.

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [x] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [x] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by mperrotti** [comment]
This seems to have resolved the type issues, but I have no idea what's causing the circular dependency errors 😢

**Comment by mperrotti** [comment]
I have no idea why we're seeing this type error in the `size` check:
```
src/drafts/MarkdownEditor/Footer.tsx(60,12): error TS2322: Type '{ icon?: ComponentType<{}> | null | undefined; leadingIcon?: ComponentType<{}> | null | undefined; trailingIcon?: ComponentType<{}> | null | undefined; ... 274 more ...; fileDraggedOver: boolean; }' is not assignable to type 'Partial<ButtonProps>'.
  Types of property 'variant' are incompatible.
    Type 'import("/home/runner/work/react/react/src/drafts/Button2/types").VariantType | undefined' is not assignable to type 'import("/home/runner/work/react/react/src/Button/types").VariantType | undefined'.
      Type '"outline"' is not assignable to type 'VariantType | undefined'.
Error: The process '/usr/local/bin/npm' failed with exit code 2
```

I can't reproduce this error locally when running `npm run test:type-check` or `npm run build`. I have a feeling this is some strange caching issue. Does anybody have any ideas?

**Comment by mperrotti** [comment]
@broccolinisoup - @joshblack found the problem! It's checking out `next-major` to test against the size of this branch, so it fails when it runs `build` on _that_ branch, not this one.

I think we can merge this once it gets approved 🙂

**Review by joshblack — APPROVED** [review]
Looks great! +1 to what was shared above, I think the size ci check is failing because the upstream branch is failing. Once this merges to address it we should we good to go 👍

**Pull request merged**
