### PR TITLE
Adding Emoji Picker API doc

### PR DESCRIPTION
**Pull request by dusave**
Describe your changes here.

Adds the Emoji Picker API doc

### Screenshots

emoji picker

### Merge checklist

- [ ] Added/updated tests
- [x] Added/updated documentation
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

### CODE REVIEW

**Comment by pksjce** [comment]
This is so cool. 
The custom category is the tabs on the top? And it converts icons to emojis?

**Comment by dusave** [comment]
@pksjce The custom categories are for any additional categories the user might need in addition to the standard unicode emoji set, such as our GitHub category. Each category contains an icon for the tab bar on top as well as an array of emojis (in the form of React Nodes) which can be images, other components, etc.

**Comment by pksjce** [comment]
Would be good to document what arguments are returned in `onSelect`? I'm not sure what to expect out of that callback.
Also do you think any of the parts will be optional? Like the searchbar? And do you think we'll need a lite down version of the picker too?

**Comment by dusave** [comment]
Interesting questions 🤔 I could see both. Toggling the search bar would be easy enough, but a compact view would require thought and designs. That said, I agree that a compact view could be valuable for certain use cases.

**Pull request closed without merging**
