### PR TITLE
fix: prevent closing menu when `event.preventDefault()` is called on `ActionList.Item`'s `onSelect` handler

### LINKED ISSUE #3162: `<ActionList.Item>`: event in `onClick` can be canceled, but it cannot be canceled in `onSelect`
### Description

Calling `event.preventDefault()` in the `onSelect` handler of `ActionList.Item` does not prevent closing the context menu. But it does work in `onClick`.

https://user-images.githubusercontent.com/39992/231557759-c14d4fd9-24c4-46a5-90b2-6d49ce7373f1.mov

I want to delay closing the context menu in order to give a user a visual feedback when something gets copied in their clipboard

https://user-images.githubusercontent.com/39992/231558448-21e32f60-a7ce-486a-99ed-9cbcb2c107b8.mov

It works when using the `onClick` handler. But that makes it inaccessible to keyboard users.

I would expect that calling `event.preventDefault()` in the `onSelect` handler would prevent closing the menu so that I can do it manually when selecting the item with the mouse or they keyboard.

### Steps to reproduce

https://stackblitz.com/edit/github-primer-action-test?file=App.tsx

### Version

35.24.0

### Browser

Chrome

### PR DESCRIPTION
**Pull request by gr2m**
Closes #3162

### Screenshots

https://user-images.githubusercontent.com/39992/231614248-7c26e213-c5cd-4c99-9b32-2542afc11a7c.mov

### Merge checklist

- [x] Added/updated tests
- [x] Added/updated documentation
- [x] Tested in Chrome
- [x] Tested in Firefox`*`
- [x] Tested in Safari
- [ ] Tested in Edge

`*` Selecting the single option doesn't work in Firefox, but I'm pretty sure that is an unrelated bug. When the menu has 2 or more items, selecting an item with keyboard navigation works in Firefox.

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by gr2m** [comment]
I'm surprised that neither my docs change nor my storybook example show up in the preview deplyoment.

**Comment by gr2m** [comment]
I now see an error when running tests locally that I don't think is related to my changes?

image

**Comment by gr2m** [comment]
> @gr2m Ouch that's not good. I'll debug why there's a new error here!

Given the error

> Error: Input required and not supplied: app_id

I assume that the problem is that `app_id` is set from a repository secret. Given that my pull request is coming from a fork, that secret is not set, hence the error.

**Comment by siddharthkp** [comment]
Hi! 

I re-implemented the changes in https://github.com/primer/react/pull/3314, hope that's okay! It's 99% the same as this pull request

**Comment by gr2m** [comment]
> Based on your repro/story, I implemented the change from scratch in #3314, hope that's okay! It's 99% the same as this pull request

no problem. You can set your PR to close this one once merged

**Comment by siddharthkp** [comment]
`CI / build-components-json` isn't set up for forks yet 😢 

So I'm going to merge this PR into a primer/react branch [primer:gr2m-patch-1](https://github.com/primer/react/tree/gr2m-patch-1) first and hopefully that should keep your contribution!

**Pull request merged**
