### PR TITLE
test(TabNav): remove nested <a> from test

### PR DESCRIPTION
**Pull request by joshblack**
Remove the nested `<a>` from `TabNav.Link`. This helps to avoid the following `validateDOMNesting` error that comes from React:

```
  console.error
    Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
        at a
        at a
        at StyledComponent (/Users/joshblack/gh/primer/react/node_modules/styled-components/dist/styled-components.cjs.js:1950:5)
        at TabNav__TabNavLink
        at div
        at StyledComponent (/Users/joshblack/gh/primer/react/node_modules/styled-components/dist/styled-components.cjs.js:1950:5)
        at TabNav__TabNavTabList
        at nav
        at StyledComponent (/Users/joshblack/gh/primer/react/node_modules/styled-components/dist/styled-components.cjs.js:1950:5)
        at TabNav__TabNavNav
        at div
        at StyledComponent (/Users/joshblack/gh/primer/react/node_modules/styled-components/dist/styled-components.cjs.js:1950:5)
        at TabNav__TabNavBase
        at children (/Users/joshblack/gh/primer/react/src/TabNav.tsx:31:18)
        at div
        at StyledComponent (/Users/joshblack/gh/primer/react/node_modules/styled-components/dist/styled-components.cjs.js:1950:5)
        at Box
        at WrapperComponent (/Users/joshblack/gh/primer/react/node_modules/@wojtekmaj/enzyme-adapter-utils/src/createMountWrapper.jsx:46:26)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at validateDOMNesting (node_modules/react-dom/cjs/react-dom.development.js:10083:7)
      at createInstance (node_modules/react-dom/cjs/react-dom.development.js:10181:5)
      at completeWork (node_modules/react-dom/cjs/react-dom.development.js:19464:28)
      at completeUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22812:16)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22787:5)
```

This also updates the test to reference only the tab and no longer includes the link.

### CODE REVIEW

**Review by broccolinisoup — COMMENTED** [review]
Looks like this test is written recently and seems like [a valid case](https://github.com/primer/react/pull/2367) but should it be a `link` ? In the PR description, it mentions about a case where there is a nested button inside the tab so maybe instead of removing this test case, we can use a `button` element and still make sure to cover nested buttons test?

**Comment by joshblack** [comment]
@broccolinisoup I think what they end up doing in Memex is changing the container `<a>` to a div for the "active tab" and so I could try doing that for the test to keep it in place 👀

**Comment by joshblack** [comment]
bump @siddharthkp @broccolinisoup let me know if you have any questions!

**Comment by broccolinisoup** [comment]
> @broccolinisoup I think what they end up doing in Memex is changing the container `<a>` to a div for the "active tab" and so I could try doing that for the test to keep it in place 👀

Ah I see. Thanks for clarification! I feel like we are good without testing this case as it is very specific to their implementation and not necessarily a part of the TabNav functionality

**Review by broccolinisoup — APPROVED** [review]

**Pull request merged**
