### PR TITLE
Add aria-label to Spinner component

### PR DESCRIPTION
**Pull request by owenniblock**
Closes https://github.com/github/primer/issues/2202

This adds a new option for setting the accessible label of the Spinner component. When it's not provided, we default to "Loading" so you have to intentionally hide the element with `label=""`. Where we find Loading state is communicated to screenreader users twice in dotcom, we can set this label value to "", I have intentionally opted for the most accessible default so it over communicates rather than under-communicating the loading state.

#### New

`label` option on Spinner component. Defaults to "Loading". When set (or left as default) it adds `aria-label={label}` to the Spinner's svg.

Adds `role="img"` to the svg element.

If the `label` is set to an empty string, it adds `aria-hidden='true'` to the svg element.

### Rollout strategy

- [ ] Patch release
- [x] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan
- [ ] None; if selected, include a brief description as to why

### Merge checklist

- [x] Added/updated tests
- [x] Added/updated documentation
- [ ] Added/updated previews (Storybook)
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [x] Tested in Edge
- [ ] (GitHub staff only) Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

### CODE REVIEW

**Comment by owenniblock** [comment]
So interestingly, the loading spinner is used on TextInput (via TextInputInnerVisualSlot) - need to work out whether we want to make it aria-hidden or not 🤔

**Review by broccolinisoup — COMMENTED** [review]
Hello @owenniblock 👋🏻 We have an open [github.com/github/primer/discussions/2976](Spinner API discussion) that  @mperrotti created, sorry if you already know about it or discussed it somewhere else. I just wanted to make sure to link them and would love to understand their overlap. 

Thank you!! 🙏🏻

**Comment by owenniblock** [comment]
@broccolinisoup I had not seen that, thanks for bringing it to my attention!

**Comment by owenniblock** [comment]
Converting to draft because there's ongoing discussions about this component.

**Comment by owenniblock** [comment]
Going to close this. We need to handle it differently anyway!

**Pull request closed without merging**
