### PR TITLE
Add flex to timeline item

### LINKED ISSUE #1402: Timeline.Item alignment
**Describe the bug**
The `Timeline.Item` component seems to be rendering wrong:

**To Reproduce**
1. Implement the Timeline and include a timeline item (for example [as shown in the docs](https://primer.style/react/Timeline))
2. Observe result

**Expected behavior**
The item content should be aligned properly

**Screenshots**
Schermafbeelding 2021-09-03 om 11 30 09

**Desktop:**
 - OS: [macOS]
 - Browser [Safari]
 - Version [14.1.2]

**Additional context**
As far as I can tell the `display:flex;` style is missing.
I created a pull request (#1403) but am not sure if done correctly. (first time contributing 😺)

### PR DESCRIPTION
**Pull request by mathiasbosman**
Added `display:flex;` to the `Timeline.Item` component. 

Closes #1402

### Merge checklist
- [X] Added/updated tests
- [ ] Added/updated documentation
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

### CODE REVIEW

**Comment by colebemis** [comment]
👋  Hi, @mathiasbosman! Thanks for the PR. Could you explain what problems `display: flex` fixes here?

**Comment by mathiasbosman** [comment]
> 👋  Hi, @mathiasbosman! Thanks for the PR. Could you explain what problems `display: flex` fixes here?

I added a screenshot in the issue #1402. The content of the item is sticking to the timeline. 

It's visible in the docs as well: https://primer.style/react/Timeline

Unless this is intended?

**Comment by colebemis** [comment]
Ah, perfect. Thank you for fixing this!

**Review by colebemis — APPROVED** [review]
❤️

**Pull request merged**
