### PR TITLE
Updates `Button` dev stories related to `sx` prop text color contrast

### PR DESCRIPTION
**Pull request by lindseywild**
Closes https://github.com/github/accessibility-audits/issues/5512.

Adds an explicit background color to the example button using the `sx` prop to ensure color contrast is passing in light and dark mode.

### Before
screen shot of the primer react storybook button story, showing the 'medium red' button has a gray background and red text with a failing color contrast ratio

### After
screen shot of the primer react storybook button story, showing the 'medium red' button has a light gray background and red text with a passing color contrast ratio

#### Changed

Dev testing storybook story only for visual regression changes. No customer facing impact.

### Rollout strategy

- [ ] Patch release
- [ ] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan
- [x] None; if selected, include a brief description as to why - updates dev only stories

### Testing & Reviewing

Open the "Dev Only" > "Test Sx Prop" Button storybook story, verify changes

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [x] Added/updated previews (Storybook)
- [x] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [x] Tested in Chrome
- [x] Tested in Firefox
- [x] Tested in Safari
- [x] Tested in Edge
- [ ] (GitHub staff only) Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

### CODE REVIEW

**Review by keithamus — APPROVED** [review]
LGTM but I don't know if @langermank or @lukasoppermann wants to review if we should use a token here?

**Comment by siddharthkp** [comment]
Hi! 

Sorry, just checking, why are we fixing the storybook instead of the component source? (either in tokens or in the component)

**Review by langermank — APPROVED** [review]

**Comment by lindseywild** [comment]
Good question! This was an audit issue against the storybook specific dev instance. The colors are hard-coded to make sure we can test the `sx` prop is working as expected, from my understanding!

**Comment by lindseywild** [comment]
@langermank Thank you! I removed the changeset (I didn't realize this wasn't required!), and removed the unrelated snapshot tests that were accidentally added. Ready for another review 🙇🏻‍♀️

**Review by keithamus — APPROVED** [review]

**Review by khiga8 — APPROVED** [review]
🚀

**Pull request merged**
