### PR TITLE
docs: add story sort function

### PR DESCRIPTION
**Pull request by joshblack**
#### Changelog

**New**

**Changed**

- Update `storySort` to a function pattern to enable custom sorting of sections, in particular when nested

**Removed**

### CODE REVIEW

**Comment by colebemis** [comment]
Is it possible to sort the Playground story above the subcomponent Playgrounds?

CleanShot 2022-11-04 at 12 02 13

Ideal order:
- Default
- Playground
- Group Playground
- Item Playground
- Link Item Playground

**Comment by joshblack** [comment]
@colebemis can definitely try!

**Comment by joshblack** [comment]
@colebemis just pushed something up that should do the trick, let me know if that's what you were thinking!

**Review by langermank — APPROVED** [review]
Thank you! 🚀

**Pull request merged**
