### PR TITLE
Added fix for issue #3884 - AvatarStack disableExpand and rightAlign don't work together

### PR DESCRIPTION
**Pull request by cs25-esc**
- Fixes https://github.com/primer/react/issues/3884

This fix resolves:

The avatars will not expand if alignRight prop is True and disableExpand prop is True.
Every combination works as expected.

https://github.com/primer/react/assets/68850280/c1a88b6d-a913-4157-87fd-fc03c43559b5

### CODE REVIEW

**Review by broccolinisoup — COMMENTED** [review]
Hi @cs25-esc 👋🏻 Thanks so much for pushing this PR! It looks good to me. Could you please add a changeset as well? https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#adding-changeset-to-your-pull-request Thank you!

**Comment by cs25-esc** [comment]
Hi @maximedegreve / @siddharthkp / @lesliecdubs could you help me with this?

**Comment by siddharthkp** [comment]
Adding changeset 👍

**Comment by cs25-esc** [comment]
Hi @siddharthkp is there any way to test CI / test (pull_request) locally ? i am suspecting the reason for failure is due to changes made in CSS class-level !

**Comment by siddharthkp** [comment]
> Hi @siddharthkp is there any way to test CI / test (pull_request) locally ? i am suspecting the reason for failure is due to changes made in CSS class-level !

Yes, if you have a local clone you can run `npm run test` and you should see the failing test. It looks like there's a snapshot that has changed. You can update that with `npm run test:update`. ([see package.json for all our scripts](https://github.com/primer/react/blob/main/package.json#L58))

Contributor docs: https://github.com/primer/react/blob/main/contributor-docs

**Comment by cs25-esc** [comment]
Hi @siddharthkp done with the snapshot update !

**Review by broccolinisoup — COMMENTED** [review]
Hello! 👋🏻 Thanks for following up with the changes. The only thing I would say is that it seems like package-lock changes in the diff includes things that are more than necessary updates. I pushed a PR to update the `@primer/react` version in the lock files https://github.com/primer/react/pull/3904 and I was wondering if that would be possible to take the package-lock changes back in this PR? They are irrelevant to the AvatarStack fix as well. Let me know if you have an concerns or questions though! Thanks again for your contribution 🙏🏻

**Comment by cs25-esc** [comment]
Hi @broccolinisoup i have made the necessary changes 👍 kindly review it please :)

**Comment by cs25-esc** [comment]
> > Hi @broccolinisoup i have made the necessary changes 👍 kindly review it please :)
> 
> Hi! Sorry maybe my comment wasn't clear. We updated the package-lock.json and package.json in another PR and it is merged now too so you don't need to push any versining changes. We should only see 3 files changed in the diff if you could please take the `package.json` and `package-lock.json` back? Thank you!

I have already made the changes `package.json` and `package-lock.json` back to its original files, sorry i am not getting what you mean

**Comment by broccolinisoup** [comment]
> I have already made the changes `package.json` and `package-lock.json` back to its original files, sorry i am not getting what you mean

No worries! If you could view the latest `@primer/react` version in the package.json ([reference](https://github.com/primer/react/blob/main/package.json#L3)), it is `36.1.0` but in this PR, the changes are taken a patch version back. 

If you do `git checkout main package.json package-lock.json` in your branch and commit and push, I believe we won't see any package changes in the diff. Let me know if I clarify anything further 🙌🏻

**Comment by cs25-esc** [comment]
> > I have already made the changes `package.json` and `package-lock.json` back to its original files, sorry i am not getting what you mean
> 
> No worries! If you could view the latest `@primer/react` version in the package.json ([reference](https://github.com/primer/react/blob/main/package.json#L3)), it is `36.1.0` but in this PR, the changes are taken back to `36.0.0`
> 
> If you do `git checkout main package.json package-lock.json` in your branch and commit and push, I believe we won't see any package changes in the diff. Let me know if I clarify anything further 🙌🏻

just did the needful, could you please verify now :)

**Comment by broccolinisoup** [comment]
HI @cs25-esc 👋🏻  There are still [5 files in the diff](https://github.com/primer/react/pull/3895/files) and that includes `package.json` and `package-lock.json`. It is probably because of the local editor settings that caused prettier not being ran and remove the EOF lines. 

Could you please run the following in your terminal?

`npm run format package.json package-lock.json` and make sure there is no `package.json` and `package-lock.json` in the diff?

**Comment by cs25-esc** [comment]
hi @broccolinisoup please review now

**Review by broccolinisoup — APPROVED** [review]
🥳

**Comment by siddharthkp** [comment]
@broccolinisoup Feel free to merge when ready :)

**Pull request merged**
