### PR TITLE
test(SelectPanel): update tests to account for more of API

### PR DESCRIPTION
**Pull request by joshblack**
As we're working more on the v1 of SelectPanel, I wanted to add some additional tests to the test suite.

This is not complete coverage but figured I'd add what I could this week and revisit another time for what was missed

#### Changed

- Update tests for Select Panel

### Rollout strategy

- [x] None; if selected, include a brief description as to why

This is a change that adds tests to Select Panel

### CODE REVIEW

**Comment by joshblack** [comment]
bump @siddharthkp when you get a sec 👀

**Review by broccolinisoup — APPROVED** [review]
Thanks so much for adding these tests 🙏🏻 

Question: I assume these are the current behaviours since all tests pass. Is there any behaviour that we know for sure that it will change after we implement the accessibility remediations? If there are some, we might want to add comments on them to help us refactor the tests later. 

Let me know if I am not making sense!

**Comment by joshblack** [comment]
@broccolinisoup my understanding since we're keeping the combobox-related functionality is that it _should_ mostly be the same behavior, if I remember right 👀

**Comment by broccolinisoup** [comment]
> @broccolinisoup my understanding since we're keeping the combobox-related functionality is that it _should_ mostly be the same behavior, if I remember right 👀

Oh this is great! Thanks for sharing that.

**Pull request merged**
