### PR TITLE
Include React 18 in peerDependencies

### PR DESCRIPTION
**Pull request by okuryu**
It includes react 18 in peerDependencies as an addition to #2196 changes.

### Screenshots

Please provide before/after screenshots for any visual changes

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by tonimelisma** [comment]
I assume this PR adds support for React 18? Is there anything blocking from merging it?

**Comment by okuryu** [comment]
As per https://github.com/primer/react/issues/2202#issuecomment-1212577860, React 18 is not yet supported, but there are plans to support it in the future. If the next release includes support for React 18, this PR could be merged as well.

**Comment by tonimelisma** [comment]
It says there's an internal issue. Why can't there be a public issue I could subscribe to in order to find out when React 18 will be supported?

**Comment by tonimelisma** [comment]
Apologies, I still don't understand. Is there a public issue I can subscribe to in order to get notified when React 18 support has been implemented? Which one is it?

**Review by siddharthkp — APPROVED** [review]
Hi! 

Sorry for the delay, we are still collecting all the compatibility issues with React 18.

Meanwhile, I think this is a pretty safe change to ship 👍

**Comment by siddharthkp** [comment]
Added to tracking issue for next release: https://github.com/primer/react/pull/2234

**Pull request merged**
