### PR TITLE
refactor(docs): move drafts to experimental

### PR DESCRIPTION
**Pull request by joshblack**
We no longer use `drafts` and encourage people to use `experimental` instead. This PR updates all instances of `drafts` to `experimental`.

#### Changed

- Update `components.json` script to no longer support drafts and only support experimental
- Update story titles that include `Drafts` to `Experimental`
- Update e2e tests that reference stories with `drafts-` to `experimental-`
- Update docs that reference stories with `drafts-` to `experimental-`

### Rollout strategy

- [x] None; if selected, include a brief description as to why

This change is related to our storybook and site versus a change to the package itself.

### Testing & Reviewing

- [ ] Verify that all instances of drafts has been removed
- [ ] Verify that no dead links occur 😅 
- [ ] If possible, would be great to test this out in the new docs site to make sure things map appropriately

### CODE REVIEW

**Review by broccolinisoup — COMMENTED** [review]
Thanks for pushing this PR Josh 🙌🏻 

I didn't come across any dead links on Storybook. It looks great! A couple of comments regarding the docs

There are still some references in the primer.style/react docs that we might want to fix:
- Navigation "Drafts" section
- "drafts" url
- The component status pill
Screenshot of the experimental Select Panel and there are three blue arrows that points of the drafts references I listed above


Also, I didn't have any luck to test out the changes in the new docs, I usually try installing the canary version of primer react in primer/design and run the docs but I got some console error. I doubt that this branch is causing it. Did you have a chance to run them on your local?

**Comment by joshblack** [comment]
Great catch @broccolinisoup! Just updated.

For the design site, I'm not sure 🤔 It's currently on v35 so feels like anything could be wrong 😅 ~~I wonder where it grabs `components.json` from then?~~

Ah, it seems like it grabs the latest version at build time:

```
// gatsby-node.esm.js

// Save the Primer React data to the GraphQL store
const content = await fetch(`https://unpkg.com/@primer/react/generated/components.json`, {redirect: 'follow'}).then(
  res => res.json(),
)
```

So it seems like for testing I should change that URL to the published version here and test that out?

**Review by broccolinisoup — APPROVED** [review]
It looks great! 🎉 I don't see any references to drafts anymore, thanks so much again!

**Comment by joshblack** [comment]
Going to close this out with the work Cameron is doing 😅

**Pull request closed without merging**
