### PR TITLE
Ability to unset emptyStateText in Autocomplete.Menu

### LINKED ISSUE #3966: Not possible to show nothing if no items match in Autocomplete
The use case is when you use `<Autocomplete>` to allow a user to ignore all the suggestions but still proceed merrily. For example, for site-search. The input widget can suggest possible search term completions that match what's been input so far, but the user types beyond any of the suggestions and submits the form to make a full site-search. 

If you set `<Autocomplete.Menu emptyStateText={false} .../>` (or `null` or `undefined`), this happens:

Autocomplete widget in action showing nothing

Earlier in the typing, when suggestions could be presented, it *looked* like this:

Autocomplete widget in action showing something

But, case in point, if the user ignores the fact that there exists no good autocomplete suggestion, completing the input does yield plenty of good site-search results:

Sample of search results listed

### PR DESCRIPTION
**Pull request by peterbe**
Closes #3966

### Changelog

When you set `emptyStateText={false}` or `emptyStateText={null}` it disables the default display which normally shows when there is `allItemsToRender.length === 0`. 

#### Changed

(Not sure what to fill in here)

### Rollout strategy

- [ ] Patch release
- [x] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan

### Testing & Reviewing

I'm actually not familiar with how to test things with Storybook. 

I've been using https://github.com/peterbe/primer-autocomplete to play. 
I run `npm run mock-server` in one terminal, and in the other I run:
```
./build-and-install-primer-react.sh && npm run dev
```
Now I can manually test my active changes in `/Users/peterbe/dev/GITHUB/primer/react`

Result:

https://github.com/primer/react/assets/26739/296ecb39-3771-4cbf-8c70-0d616610aee4

(*What's not obvious in the video is that a second after I've typed the `y` in "holly" the next thing is that hit the Enter key, which (Nextjs) redirects to the full site-search*)

What this implementation does is that it entirely disables the empty-state text by setting:
```jsx
emptyStateText={false}
```

So when the cursor is put into the input field, before any XHR can fetch anything, there are *no* items to suggest. So nothing happens and nothing is shown just because the cursor is put into the input. 
Then when you type and, after XHR loading, there's exactly 0 found suggestions, only then does it add a faux item which I watch out for in the onSubmit. 

See: https://github.com/peterbe/primer-autocomplete/blob/4af3e861a5fe8443626ec4899d1aa3f29b05b9e7/src/pages/index.tsx#L218 
and https://github.com/peterbe/primer-autocomplete/blob/4af3e861a5fe8443626ec4899d1aa3f29b05b9e7/src/pages/index.tsx#L175-L180 for the "faux" suggestion. 
And lastly, I complete the full search based on the typed input, these lines:
https://github.com/peterbe/primer-autocomplete/blob/4af3e861a5fe8443626ec4899d1aa3f29b05b9e7/src/pages/index.tsx#L224-L231

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Storybook)
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [x] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge
- [ ] Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by peterbe** [comment]
@mperrotti (CC @siddharthkp )
Be gentle! My first PR against primer. I'd love some guidance on the paperwork around writing changesets and/or how to update Storybook to examplify this new possibility. 
I'm quite fond of the net result now. It seems to be "exactly" what was concluded in the Primer A11y office hours meeting we had.

**Comment by lesliecdubs** [comment]
Hey @peterbe, thanks for the contribution ✨ ! If you're ready for review, would you please mark this draft as ready and the reviewers will get it into their queue? Thanks!

**Comment by peterbe** [comment]
@mperrotti I see that you're assigned to [the issue](https://github.com/primer/react/issues/3966)
Perhaps you can lend a helping hand how to move this PR forward. I'd unaccustomed to the Storybook side and the changeset paperwork is new to me.

**Comment by mperrotti** [comment]
Sorry for the delay @peterbe - taking a look now.

**Review by mperrotti — APPROVED** [review]

**Comment by peterbe** [comment]
I don't understand the failing CI checks. Is that anything I should heed?

**Comment by mperrotti** [comment]
We just merged a fix for those. Let me try re-running...

**Comment by mperrotti** [comment]
@peterbe - try updating your fork to pull the latest `main` branch

**Comment by peterbe** [comment]
> @peterbe - try updating your fork to pull the latest `main` branch

Did that. Same error.

**Comment by peterbe** [comment]
I think it's because https://github.com/primer/react/blob/1116586269f6fadf9127661f8aef3255b447e8a1/.github/workflows/deploy_preview.yml doesn't specify a `permissions:` at the top of the file.

**Pull request merged**
