### PR TITLE
Added `statusLabels` property to `ToggleSwitch` component to customize "On" and "Off" labels.

### PR DESCRIPTION
**Pull request by Swiftwork**
Describe your changes here.

Added `statusLabels` property to `ToggleSwitch` component to customize "On" and "Off" labels. Reason being the words "On" and "Off" aren't always applicable. For instance with a label such as "Gate", "Opened/Closed" might be more reasonable, or with "Do you want emails?" maybe you would like "Yes/No".

### Screenshots

image
image

### Merge checklist

- [ ] Added/updated tests
- [x] Added/updated documentation
- [x] Tested in Chrome
- [x] Tested in Firefox
- [ ] Tested in Safari
- [x] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by broccolinisoup** [comment]
Hi @Swiftwork 👋🏼 Thanks for the PR! For the contributions that introduce changes in the API, we recommend [creating an issue](https://github.com/primer/react/issues/new/choose) or [starting up a discussion](https://github.com/primer/react/discussions/new) to talk about the functionality, different approaches and confirm them with our design & accessibility design/engineering team to make a collective decision. I hope it is helpful!

**Review by broccolinisoup — COMMENTED** [review]
Hi @Swiftwork 👋🏼 Thanks for the PR! For the contributions that introduce changes in the API, we recommend [creating an issue](https://github.com/primer/react/issues/new/choose) or [starting up a discussion](https://github.com/primer/react/discussions/new) to talk about the functionality, different approaches and confirm them with our design & accessibility design/engineering team to make a collective decision. I hope it is helpful!

**Comment by Swiftwork** [comment]
Not stale

**Comment by mperrotti** [comment]
Thanks for contributing! If in the future we decide to edit this component, we can revisit this pull request.

Issue comment for context: https://github.com/primer/react/issues/2858#issuecomment-1424830793

**Pull request closed without merging**
