### PR TITLE
Overlay: Add proper roles w/ keyboard expectations to stories

### PR DESCRIPTION
**Pull request by TylerJDev**
We utilize `Overlay` in many different ways. Our stories for `Overlay` largely represent a modal dialog pattern. This PR aims to add proper roles with the proper keyboard expectations for those roles to each story. 

#### Changed

* Adds roles with keyboard expectations to `Overlay` stories

### Rollout strategy

- [ ] Patch release
- [ ] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan
- [x] None; if selected, include a brief description as to why (Only includes changes to Storybook examples)

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [x] Added/updated previews (Storybook)
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [x] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge
- [ ] (GitHub staff only) Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

### CODE REVIEW

**Review by anandfresh — APPROVED** [review]

**Review by francinelucca — COMMENTED** [review]
Looking good! 
One question: For the positioned overlays story, I have to hit `esc` twice to get one of the overlays to close, is this intended? In prod I see we only have to click it once. 
I also noticed the default story is not showing up neither here nor in prod, do you know what that's about? I can open a separate issue for that 
Everything else looks good to me!

**Comment by TylerJDev** [comment]
> One question: For the positioned overlays story, I have to hit esc twice to get one of the overlays to close, is this intended? In prod I see we only have to click it once.

Good catch, this seems to be because we're using an IconButton here with `Tooltip`. <kbd>Escape</kbd> will close the tooltip first before closing the dialog. I'm wondering if we should change this to a standard `<button>` with "close" as the text over an `IconButton`?

As for the default story, I believe it's because we only have a `.features` file for `Overlay`. I'm guessing this was a choice to only show features, but I'm not sure 🤔 We could create a separate issue for it and see if there are any other components w/o one.

**Comment by francinelucca** [comment]
> Good catch, this seems to be because we're using an IconButton here with `Tooltip`. Escape will close the tooltip first before closing the dialog. I'm wondering if we should change this to a standard `<button>` with "close" as the text over an `IconButton`?

Ahh I didn't notice the first `esc` was closing the tooltip, that may be ok then. Your call

Opened issue for default story: https://github.com/primer/react/issues/5183

**Review by francinelucca — APPROVED** [review]
🚀

**Pull request merged**
