### PR TITLE
Release checklist: Add after merge step for permalink

### PR DESCRIPTION
**Pull request by siddharthkp**
Today, we don't have a quick way to see the docs for an older version of primer/react that an application might be using. This [comes up](https://github.com/github/planning-tracking/discussions/1429#discussioncomment-3627233) [quite often](https://github.com/primer/react/issues/2160). 

As a bandaid, we should add the permalink of preview deployment for Release Tracking PR to the release notes after merge. (I added it for the [last 5 releases](https://github.com/primer/react/releases), [example](https://github.com/primer/react/releases/tag/v35.9.0#:~:text=Permalink%20to%20documentation))

Would be nice to automate it, if possible? cc @rezrah  

release notes with a link to the documentation

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Love it 🚀

**Review by colebemis — APPROVED** [review]

**Comment by colebemis** [comment]
Do the preview deploy links ever expire? cc @rezrah

**Comment by siddharthkp** [comment]
> Do the preview deploy links ever expire?

Probably, but [this one from 30 Jun 2022](https://github.com/primer/react/releases/tag/v35.4.0) is still active!

**Comment by siddharthkp** [comment]
> Do the preview deploy links ever expire?

Probably, but [this one from 30 Jun 2022](https://github.com/primer/react/releases/tag/v35.4.0) is still active!

**Pull request merged**
