### PR TITLE
Button API alignment

### PR DESCRIPTION
**Pull request by langermank**
This PR includes **breaking changes** to bring the PRC Button up to the agreed upon API spec and match implementation with PVC.

- Changes `leadingIcon` and `trailingIcon` to `leadingVisual` and `trailingVisual` (a pattern introduced with ActionList)
- Removes `Button.Counter` as a child component, replacing it with a `trailingVisualCount` prop. This change allows us to use the `trailingVisual` slot for counters, and also aligns better with all the other child elements within Button (visuals are props, not child components in this case.)
- Removes the `outline` button variant as we wish to only support `invisible` buttons.

### Screenshots

The only visual change is that the `outline` button variant has been removed.

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

### CODE REVIEW

**Comment by joshblack** [comment]
Hey @langermank! I've been trying to make sure all the branches are up-to-date with the new vrt workflow. I wanted to ask if you have any free time this week to update the conflicts on this PR?

**Comment by langermank** [comment]
@joshblack thanks for the reminder! I'm waiting for [this PR](https://github.com/primer/react/pull/2792) that @broccolinisoup is working with me on to land before I update this PR since I think it will resolve a lot of the conflicts here. I had to revert the original PR that _this_ PR is based on.

**Comment by langermank** [comment]
Will reopen once https://github.com/primer/react/pull/2792 merges

**Comment by langermank** [comment]
Note to self: all these changes to this PR https://github.com/primer/react/pull/2792/commits/d79fbfc695b62fd435aa842ac1f770077564809d

**Pull request closed without merging**
