### PR TITLE
fix(SelectPanel2): only bind keydown event when necessary

### LINKED ISSUE #4581: SelectPanel2 Optimization: Do not add and remove keydown listener for escape key on every render
### Description

`SelectPanel2.SelectPanel` will call `dialogEl.removeEventListener` and `dialogEl.addEventListener` on every render, because the call to `React.useEffect` is not passed an array of dependencies at this callsite: https://github.com/primer/react/blob/main/packages/react/src/drafts/SelectPanel2/SelectPanel.tsx#L195

The React docs describe this behavior here: https://react.dev/reference/react/useEffect#parameters

> If you omit this argument, your Effect will re-run after every re-render of the component.

I suspect the dependency array was an accidental omission.

Why am I filing this bug/optimization issue? 

I was interested in making a contribution to this repository, and I wanted to start with a small, low impact change. Select components are interesting to me, so I began reviewing the component to look for ways to help, and I came across this as a potential optimization. It's a nitpick, and may not have any real impact on user performance, so I understand if the maintainers want to close without addressing.

### Steps to reproduce

The following test case will fail for me when I added to https://github.com/primer/react/blob/main/packages/react/src/drafts/SelectPanel2/SelectPanel.test.tsx.

Note: This is a fairly "white box" test and relies on implementation details. I find that these kind of tests are useful to check performance optimizations, but the tradeoff is that the tests are more brittle.

```ts
// packages/react/src/drafts/SelectPanel2/SelectPanel.test.tsx
  it('should not call addEventListener on each render', async () => {
    const container = render(<SelectPanel title="title">child</SelectPanel>)
    const dialogEl = container.getByRole('dialog', {hidden: true})
    const addEventListenerSpy = jest.spyOn(dialogEl, 'addEventListener')
    const removeEventListenerSpy = jest.spyOn(dialogEl, 'removeEventListener')

    container.rerender(<SelectPanel title="title">child</SelectPanel>)
    expect(addEventListenerSpy).not.toHaveBeenCalled()
    expect(removeEventListenerSpy).not.toHaveBeenCalled()
  })
```

### Version

v36.17.0

### Browser

_No response_

### PR DESCRIPTION
**Pull request by bwittenberg**
Closes #4581

#### New

- Adds additional `jest` test coverage for the `SelectPanel`

#### Changed

- Adds optimization to `SelectPanel` so that event listeners are not added and removed on each render, but only when the effect dependencies change.

### Rollout strategy

- [x] Patch release
- [ ] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan
- [ ] None; if selected, include a brief description as to why

### Testing & Reviewing

- One of the `SelectPanel` jest test should fail if changes to `SelectPanel` are reverted.
- RT1: Regression Test 1: Panel should close when opened and escape is pressed
  - Visit the `SelectPanel` in storybook (http://<storybook-origin>/?path=/story/drafts-components-selectpanel--default)
  - Click the button, assert panel opens
  - Press the `Escape` key on the keyboard, assert panel closes

### Merge checklist

- [x] Added/updated tests
~- [ ] Added/updated documentation~
~- [ ] Added/updated previews (Storybook)~
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
  - I'm not sure about this one. Because hooks with dependencies are in use already, this code change shouldn't introduce any issues. I didn't test though, which is why I'm not checking this box.
- [x] Tested in Chrome (ran RT1 above on Chrome 124.0.6367.207)
- [x] Tested in Firefox (ran RT1 above on Firefox 126.0)
- [x] Tested in Safari (ran RT1 on Safari 17.4.1)
- [x] Tested in Edge (ran RT1 on Edge 124.0.2478.105)
- [ ] (GitHub staff only) Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

### CODE REVIEW

**Review by broccolinisoup — COMMENTED** [review]
Hello @bwittenberg 👋🏻 Thanks for pushing this PR! It looks good to me 👍🏻 I'll just ping @siddharthkp since he has greater context on SelectPanel to see if there is any concern from him!

**Comment by bwittenberg** [comment]
Hello @broccolinisoup! Appreciate the 👀. If you'd like to see any changes, I'm happy to make revisions.

**Review by siddharthkp — APPROVED** [review]
Looks good to me!

**Review by broccolinisoup — APPROVED** [review]
🎉

**Pull request merged**
