### PR TITLE
ActionMenu: Only use checkmarks in menus and improve examples

### LINKED ISSUE #3878: ActionMenu: Selected items use checkboxes instead of checkmarks
### Description

Our [multi-selection ActionMenu](https://primer.style/react/storybook/?path=/story/components-actionmenu-features--multi-select) uses checkboxes, but this is misleading because clicking them actually closes the menu instead of just selecting an option. This isn't what people usually expect from checkboxes and it's also not in line with what [our docs](https://primer.style/components/action-menu) say.

https://github.com/primer/react/assets/980622/d39af7ed-10f7-4b15-890d-00ed144e4c01

In the [Multiple Sections](https://primer.style/react/storybook/?path=/story/components-actionmenu-examples--multiple-sections) example we don't close the menu however a menu is always expected to close upon making a selection. Therefore this example is incorrect as well.

On the other hand the [Mixed Selection](https://primer.style/react/storybook/?path=/story/components-actionmenu-examples--mixed-selection) example checkmarks behaviour and it closing the menu is correct.

**Requirements**
- Menus always close upon making a selection
- Checkboxes or other form controls are not semantically available within menus
- Multi selection and single selections are indicated by a checkmark and not a checkbox

Don't confuse a multi selection [ActionMenu](https://primer.style/components/action-menu) with a [SelectPanel](https://primer.style/components/selectpanel) dialog (semantically).

### Steps to reproduce

1. Go to the [Multi Select example](https://primer.style/react/storybook/?path=/story/components-actionmenu-features--multi-select)
1. Make a selection
1. Notice how the menu doesn't close and incorrect checkboxes are being used to indicate the selection

I've also checked our internal Figma library and the component is implemented correctly there.

### Version

v35.32.2

### Browser

Safari

### PR DESCRIPTION
**Pull request by maximedegreve**
Closes #3878 

### Changelog

- Always use checkmarks for menus instead of checkboxes
- Improve the examples

#### Before / After

Storybook example (Before/After)
Storybook example (Before/After)
Storybook example (Before/After)
Storybook example (Before/After)

### Rollout strategy

- [x] Patch release
- [ ] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Added/updated previews (Storybook)
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge
- [ ] Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by maximedegreve** [comment]
I'm currently investigating which product areas will be impacted by this change and will outline them below.

## Projects

In roadmap project boards, the "milestones" menu will be updated to use checkmarks instead. This change aligns it with other menus, such as the "date fields" menu. However, there's an issue with consistency in how these menus behave. Some close immediately after a selection is made, while others stay open. Ideally, dropdown menus should close once a selection is made. If they need to stay open, a SelectPanel with a dialog and a close button should be used for better accessibility.

Action Required: While the above issue is not critical, it's important to notify the projects team to address these inconsistencies.

Screenshot of dropdown menus in projects

**Review by joshblack — APPROVED** [review]
LGTM from the implementation side! 👍 What would the recommended way be to roll this our in the next release cycle?

**Comment by lesliecdubs** [comment]
@joshblack or @siddharthkp, does validating the changes in this PR fall clearly into either of the epics you are directly working on right now given the impact on `ActionMenu` a11y and potentially `SelectPanel` work? If so, we could try to add scope to fix dotcom to those epics. If not, we might need to explicitly plan for how to roll this out in dotcom as part of Q3 work. 

What do you think?

**Comment by siddharthkp** [comment]
> does validating the changes in this PR fall clearly into either of the epics you are directly working on right now given the impact on ActionMenu a11y and potentially SelectPanel work?

Doesn't fall into my path in SelectPanel, sorry! Happy to look into it outside the epic, of course

**Comment by maximedegreve** [comment]
@lesliecdubs @joshblack Internally [this pull request was merged ](https://github.com/github/github/pull/303043) which unblocks this. Are you both happy to merge this and agree that [the above impact is minimal](https://github.com/primer/react/pull/3994#issuecomment-1835861073)?

**Comment by lesliecdubs** [comment]
@maximedegreve I'm comfortable with merging if @siddharthkp also approves. Should we verify with @tallys from the design perspective as well?

**Comment by siddharthkp** [comment]
> @maximedegreve: I believe it's wise to wait for the Notifications and Memex team to adjust to the above changes before we proceed with the merge.

Hi 👋 , do you know if the changes you asked for in notifications and memex have been merged?

**Comment by maximedegreve** [comment]
@siddharthkp Memex is informed about the updates. However, these won't cause any disruptions because they only alter the appearance. Besides, the current menu behavior there is already inconsistent as described above.

**Pull request merged**
