### PR TITLE
[checkbox] Show Checkmark to users with reduced-motion enabled

### PR DESCRIPTION
**Pull request by kendallgassner**
When testing Stylelint-a11y rules I noticed that our Checkbox component does not show the checkmark when reduced motion is turned on:
 
A screenshot of the Checkbox Component on Storybook. The checkbox is selected and filled in with a blue background; however the checkmark is not visible.

Closes # (type the issue number after # if applicable; otherwise remove this line)

### Screenshots

Please provide before/after screenshots for any visual changes

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Review by TylerJDev — APPROVED** [review]
Very nice! ✨

**Comment by kendallgassner** [comment]
@joshblack The animation is very minimal, I _think_ it would be okay to leave in the motion for reduced-motion users.
 
@ericwbailey or @ichelsea could you also weigh in?

**Comment by ericwbailey** [comment]
My take is that the animation is minimal and user-initiated. I'd feel comfortable removing the query.

**Comment by ichelsea** [comment]
@kendallgassner I agree with Eric!

**Review by joshblack — APPROVED** [review]

**Pull request merged**
