### PR TITLE
Extract Storybook content into subdirectory

### PR DESCRIPTION
**Pull request by jclem**
🚨 🏗️ **WIP:** Work in progress 🚧 🚨

Closes https://github.com/primer/react/issues/1849 by extracting Storybook files and configuration to the stories/ directory.

### Screenshots

Please provide before/after screenshots for any visual changes

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by jclem** [comment]
All tests are passing except for the `checkStoriesForAxeViolations` tests, which `require` the stories themselves.

Now that the root and stories/ directories have separate package.json manifests and node_modules, it appears that we may have two separate instances of React installed. Temporarily, this can be resolved by `rm -r`-ing the `stories/node_modules` directory, which wipes out the additional React package installation, but I'm not sure what a permanent fix looks like, yet.

**Comment by colebemis** [comment]
👋  I know this isn't done yet, but I just wanted to mention that this approach would move us away from the [file structure ADR](https://github.com/primer/react/blob/main/contributor-docs/adrs/adr-XXX-file-structure.md) that @jfuchs proposed last quarter. Not a dealbreaker but something to consider.

**Comment by jclem** [comment]
@colebemis I don't think we have a choice, unfortunately, unless we want to continue having Primer React ship types from Storybook in its build output. This happens _just_ because those types are in our `node_modules` directory when we compile.

The only other solution I might try is to restrict the `typeRoots` in `tsconfig.build.json`, but it'll mean listing each build dependency's `node_modules` types path specifically.

**Comment by jclem** [comment]
Closed in favor of https://github.com/primer/react/pull/1855

**Pull request closed without merging**
