### PR TITLE
Fix label colors for border and text

### PR DESCRIPTION
**Pull request by lukasoppermann**
Label colors for border and text were mixed up for variants `done` and `sponsors`. 

This leads to an a11y issue were text colors don't pass.

### CODE REVIEW

**Review by josepmartins — APPROVED** [review]
LGTM! just left a non blocking comment/question

**Comment by lukasoppermann** [comment]
> > This leads to an a11y issue were text colors don't pass.
> 
> Just curious about this, aren't the `fg` and `emphasis` values the same? what's the a11y issue?
> 
> Screenshot 2022-10-27 at 15 39 33

Not in dark mode:

```js
  done: {
    fg: get('scale.purple.4'),
    emphasis: get('scale.purple.5'),
    muted: alpha(get('scale.purple.4'), 0.4),
    subtle: alpha(get('scale.purple.4'), 0.15)
  },
  sponsors: {
    fg: get('scale.pink.4'),
    emphasis: get('scale.pink.5'),
```

**Comment by josepmartins** [comment]
> Not in dark mode:

Gotcha, thank you! 👍

**Comment by lukasoppermann** [comment]
@colebemis or @rezrah can you help me with the failing changeset? What do I need to do?

**Comment by broccolinisoup** [comment]
> @colebemis or @rezrah can you help me with the failing changeset? What do I need to do?

Hi @lukasoppermann 👋🏼  It is complaining because there is no changeset file for this change. You can read about changesets [here](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) but for a brief intro, we use them for release tracking purposes. Changeset files include info about what we need to release and what level of versioning i.e. patch/minor/major (ref: [semver ](https://semver.org/))) I believe this PR is a patch. And you can run `npx changeset` on your branch and answer the questions that pop put and it should generate a changeset file and please commit that changeset file after. That should make the error go away and have a proper changeset for the release tracking. Let us know if you still have issues 🙂

**Pull request merged**
