### PR TITLE
Add AutocompleteContext to the Autocomplete component's exports

### PR DESCRIPTION
**Pull request by willglas**
Added `AutocompleteContext` to the `Autocomplete` component's exports. This allows consumers to customize the `Autocomplete` component's behavior to a much larger degree.

### Screenshots

No visual changes.

### Merge checklist

- [ ] Added/updated tests
- [x] Added/updated documentation
- [x] Tested in Chrome
- [x] Tested in Firefox
- [x] Tested in Safari
- [x] Tested in Edge

I wasn't sure if updating documentation was necessary, let me know if that's required for this change to go in.

### CODE REVIEW

**Review by mperrotti — APPROVED** [review]

**Comment by willglas** [comment]
@mperrotti it looks like you might need to kick off some CI?

**Comment by mperrotti** [comment]
@colebemis - the new CI issue with package-lock.json is happening.

How did you get it to work last time?

Here's what I've tried:
- Re-running the checks
- `rm -rf node_modules && npm cache clear -f && npm i` on this branch after merging `main`

cc @siddharthkp since you're not as busy with the design summit.

**Comment by mperrotti** [comment]
@willglas - Could you open a PR as a branch directly off of this repo? Org tokens aren't propagating or being respected, so deployments aren't working for PRs from a forked repo.

**Comment by mperrotti** [comment]
Hey @willglas  - I’m looking into this now. Worst-case scenario, I’ll cherry-pick your commits onto a new branch and open a PR

**Comment by mperrotti** [comment]
@willglas - you should have received an invite

**Pull request closed without merging**
