### PR TITLE
chore(release): v36.0.0

### PR DESCRIPTION
**Pull request by joshblack**
Closes https://github.com/primer/react/pull/3384

## Review Checklist

| PR | Description | Reviewer | Reviewed | 
| :----------- | :---------- | :------- | :------- |
| [#3569](https://github.com/primer/react/pull/3569) | Update styled-components and related dependencies to v5.x | @joshblack | ✅ |
| [#3542](https://github.com/primer/react/pull/3542) | Remove components from deprecated | @broccolinisoup | ✅ |
| [#2893](https://github.com/primer/react/pull/2893) | Button API Changes | @langermank | ✅ |
| [#3313](https://github.com/primer/react/pull/3313) | Remove deprecated `extralarge` variant | @broccolinisoup | ✅ |
| [#3735](https://github.com/primer/react/pull/3735) | Remove StyledOcticon component | @joshblack | ✅ |
| [#3396](https://github.com/primer/react/pull/3396) | Deprecates FilterList and FilteredSearch components | @joshblack  | ✅ |
| [#3399](https://github.com/primer/react/pull/3399) | Makes @types/styled-components an optional peer dependency | @joshblack | ✅ |
| [#3240](https://github.com/primer/react/pull/3240) | Update minimum version for react and react-dom to v18 | @joshblack |  ✅ |
| [#3544](https://github.com/primer/react/pull/3544) | Remove `DropdownButton` and `DropdownMenu` from deprecated | @broccolinisoup | ✅ |
| [#3387](https://github.com/primer/react/pull/3387) | Remove deprecated ActionList component | @broccolinisoup  | ✅||
| [#3414](https://github.com/primer/react/pull/3414) | Removes 'warning' option  | @broccolinisoup | ✅  |
| [#3319](https://github.com/primer/react/pull/3319) | Remove support for `activeClassName`  | @broccolinisoup | ✅  |
| [#3556](https://github.com/primer/react/pull/3556) | Ensure ActionList item has `border-radius` on hover with `full` variant | @langermank | ✅ |
| [#3367](https://github.com/primer/react/pull/3367) | Use createRoot instead of ReactDOM.render for React 18 compatibility | @siddharthkp | ✅ |
| [#3557](https://github.com/primer/react/pull/3557) | Use IconButton instead of ButtonClose in v1 Dialog | @siddharthkp | ✅ |
| [#3538](https://github.com/primer/react/pull/3538) | FilteredActionList now uses new ActionList as a base | @siddharthkp | ✅ |

### CODE REVIEW

**Review by pksjce — APPROVED** [review]

**Review by broccolinisoup — APPROVED** [review]
I am approving the parts that I reviewed! Looking so good!

Also, if anyone needs a hand with reviewing any of the other parts, let me know!

**Comment by broccolinisoup** [comment]
@joshblack The only change I couldn't confirm was the [generated/component.json](https://github.com/primer/react/pull/3414/files#diff-8778522dbf1a0c66d558a9046576374ffa9cdfc691932c3599b6330cb7991bed) from https://github.com/primer/react/pull/3414 since we don't include it anymore in the source due to the deploy job didn't run.

**Comment by siddharthkp** [comment]
- Found missing docs updates and a layout bug in https://github.com/primer/react/pull/3386, addressing the docs update in https://github.com/primer/react/pull/3858

Have not addressed the layout bug yet:

| Before | After |
|--------|--------|
| space between pane and content | no space between pane and content |

**Comment by joshblack** [comment]
Thanks @siddharthkp! Opened up: https://github.com/primer/react/issues/3859 for the second issue and will try to tackle it today 👍

**Pull request merged**
