### PR TITLE
Fixed: Ensure Header component uses proper semantic header HTML tag

### PR DESCRIPTION
**Pull request by amarmanhala**
Changed div tag to HTML semantic element for Header component

Issue #2870 

### Merge checklist

- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by amarmanhala** [comment]
Hi @joshblack, This is my PR. Please can you guide me if there is anything that I missed or any advice? Thanks

**Comment by amarmanhala** [comment]
Thank you @joshblack for your guidance 🤗. I have committed test snapshots now. Hopefully, it works now.

**Comment by joshblack** [comment]
@amarmanhala seems like just one final change, in the test file for `Header` (`src/__tests__/Header.test.tsx`) there is a test that asserts on the tagName that needs to be updated:

```diff
  it('renders a <div> and <a>', () => {
-    expect(render(<Header />).type).toEqual('div')
+    expect(render(<Header />).type).toEqual('header')
    expect(render(<Header.Link />).type).toEqual('a')
  })
```

After that you should be good to go! 🥳

**Comment by amarmanhala** [comment]
Thank you @joshblack for your guidance.

**Comment by joshblack** [comment]
Thanks so much for your contribution @amarmanhala! 🙌 🥳

**Pull request merged**
