### PR TITLE
SegmentedControl: Reformat stories and add e2e tests

### PR DESCRIPTION
**Pull request by broccolinisoup**
Tracking issue: https://github.com/github/primer/issues/1488

Add storybook stories for `SegmentedControl`

**Checklist**

- [x] Ensure your chosen component has a component directory in the src directory
- [x] Ensure the component has a root story file in the component directory
- [x] Ensure that the root story file exports a Default story
- [x] (Optional) Create a Playground story
- [x] Move all other stories for the component into a .features.stories.tsx file
- [x] Opt the component into storybook tests
- [x] (Optional) Create visual regression tests for the component

### CODE REVIEW

**Comment by joshblack** [comment]
@broccolinisoup tried to help out with some of the weirdness with the VRT and AAT jobs after talking with @langermank earlier today. Hope that was okay, let me know and I can 100% revert stuff that I changed!

**Comment by broccolinisoup** [comment]
> @broccolinisoup tried to help out with some of the weirdness with the VRT and AAT jobs after talking with @langermank earlier today. Hope that was okay, let me know and I can 100% revert stuff that I changed!

Oh not at all @joshblack! I am very appreciative that you resolved the failings. Thank you so much, it looks great!

**Review by joshblack — APPROVED** [review]
Looks great! ✅ 

Only thing I noticed was actually unrelated to your changes where the file for features was named `SegmentedControlFeatures.stories.tsx` when I think it should be named `SegmentedControl.features.stories.tsx`

**Comment by broccolinisoup** [comment]
> Looks great! ✅
> 
> Only thing I noticed was actually unrelated to your changes where the file for features was named `SegmentedControlFeatures.stories.tsx` when I think it should be named `SegmentedControl.features.stories.tsx`

Oh let me rename it - good catch!

**Pull request merged**
