### PR TITLE
Dialog v2: Move files, reformat stories and add e2e tests

### PR DESCRIPTION
**Pull request by broccolinisoup**
Tracking issue: https://github.com/github/primer/issues/1488

Add storybook stories for `Dialog2 (draft)`

**Checklist**

- [x] Ensure your chosen component has a component directory in the src directory
- [x] Ensure the component has a root story file in the component directory
- [x] Ensure that the root story file exports a Default story
- [x] (Optional) Create a Playground story
- [x] Move all other stories for the component into a .features.stories.tsx file
- [x] Opt the component into storybook tests
- [x] (Optional) Create visual regression tests for the componentDescribe your changes here.

Closes # (type the issue number after # if applicable; otherwise remove this line)

### Screenshots

Please provide before/after screenshots for any visual changes

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Looks good! ✨ 

For naming, since the component is `Dialog` from drafts would it make sense to keep the name as `Dialog` and use the status field (draft) to namespace it? Instead of `Dialog2`. I think it was confusing initially for me to see `Dialog2` but the export itself was still `Dialog`

Hope that makes sense 😅

**Comment by broccolinisoup** [comment]
> keep the name as Dialog and use the status field (draft) to namespace it

Sorry @joshblack I didn't understand what you mean 😬 

>I think it was confusing initially for me to see Dialog2 but the export itself was still Dialog

That is fair! The reason I did this, we did the similar convention for the UnderlineNav because both versions (the current and the draft version) lives in the src folder but both exports as `UnderlineNav`; one from the main bundle other from draft. I know it is confusing 😭 and happy to change it! I would love if you could explain me the alternative way you are suggesting a little bit more! Thank you 🙌🏻

**Comment by joshblack** [comment]
@broccolinisoup totally makes sense! If that conventions works then totally works for me 👍

**Comment by joshblack** [comment]
@broccolinisoup ah! Sorry for the extra commit, tried to revert it as soon as I realized 😅 Totally thought I was on a different branch.

**Pull request merged**
