### PR TITLE
Revert "Revert "Add support for nested submenus to `ActionMenu`""

### PR DESCRIPTION
**Pull request by iansan5653**
Reverts primer/react#4472

### CODE REVIEW

**Comment by pksjce** [comment]
Hi @iansan5653! Would be great to get this code back in `ActionMenu`. Could you list any todos to push this PR to ready and merge it?
I'm happy to take it over incase you cannot prioritise it.

**Comment by pksjce** [comment]
What I understand is that there is no particular issue in this PR itself. But after this is merged in, we need to upgrade dotcom to use this component instead of `NestableActionMenu`. Approving this PR.

**Comment by siddharthkp** [comment]
Hi @iansan5653, our canary publishing is working smoothly again, created a integration PR to check what were the errors: https://github.com/github/github/pull/323719

**Comment by iansan5653** [comment]
Thank you! Planning to get this worked out this week

**Pull request merged**
