### PR TITLE
[Bug] Leading & Trailing Visual Colors for Button

### PR DESCRIPTION
**Pull request by jesskuo4**
Describe your changes here.
- Changed the Leading and Trailing Visual Icon Colors for the Button Component to `fg.muted`
- Change ButtonCounter font size to 0 (12px) 

Closes https://github.com/github/primer/issues/2373

### Screenshots
| Before | After | 
| -- | -- |
| Before image of trailing/leading icons | After image of trailing/leading icons
| Before image of counter with wrong size | After image of counter with corrected size |

Please provide before/after screenshots for any visual changes

### Merge checklist

- [x] Added/updated tests
- [ ] Added/updated documentation
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by maximedegreve** [comment]
Boom 🎉

**Found two small things:**

1️⃣ The [icon button](https://primer-c250feac6f-13348165.drafts.github.io/Button#icon-only-button) example is still not muted.

2️⃣ Then the counter is vertically not aligned centred.

Screenshot 2023-06-24 at 13 19 35

**Review by broccolinisoup — APPROVED** [review]
🥳

**Comment by broccolinisoup** [comment]
Oops, I just saw the two small issues Maxime mentioned 👀 Overall, it is looking pretty good 🎉

**Comment by jesskuo4** [comment]
> Boom 🎉
> 
> **Found two small things:**
> 
> 1️⃣ The [icon button](https://primer-c250feac6f-13348165.drafts.github.io/Button#icon-only-button) example is still not muted.
> 
> 2️⃣ Then the counter is vertically not aligned centred.
> 
> Screenshot 2023-06-24 at 13 19 35

Hi @maximedegreve! 👋  Thank you so much for pointing these two things out and waiting, I wanted to double check some things with my mentor, Katie, before responding but here is a short response: 

Regarding num1 of this comment, I was thinking that it might be better to keep the icon button only to remain as fg.default as the current **disabled** icon button uses the fg.muted look. It might be good to consider keeping it this way so users can differentiate the status of the button. We also have an invisible variant, which has a muted color by default but when it becomes disabled, it will look more like this with a background (its broken right now in PRC). What are your thoughts?
image

Regarding num2, I tried correcting the issue. However, I shared with Katie and she mentioned how to solve the problem, we have to change how the the counter button is layered, which might cause other issues. She is currently looking into this and will get back to you! 

Thank you!! 😄

**Pull request merged**
