### PR TITLE
Export new UnderlineNav in the main bundle and move the older one to the deprecated bundle - Major release

### PR DESCRIPTION
**Pull request by broccolinisoup**
Describe your changes here.

Closes # (type the issue number after # if applicable; otherwise remove this line)

### Screenshots

Please provide before/after screenshots for any visual changes

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by joshblack** [comment]
Hey @broccolinisoup! I've been trying to make sure all the branches are up-to-date with the new vrt workflow. I wanted to ask if you have any free time this week to update the conflicts on this PR?

**Comment by broccolinisoup** [comment]
> Hey @broccolinisoup! I've been trying to make sure all the branches are up-to-date with the new vrt workflow. I wanted to ask if you have any free time this week to update the conflicts on this PR?

Thanks @joshblack! I updated the branch and resolved all conflicts. The VRT and AAT checks are failing though and the `Update snapshots` labels didn't work either. I am really not sure what is going on 😢

**Comment by joshblack** [comment]
Hey @broccolinisoup! 👋 

I think when the id of the stories change (like removing drafts) the tests themselves will need to be changed. I pushed up a commit that I think should tackle the new paths 🤞

**Comment by broccolinisoup** [comment]
> Hey @broccolinisoup! 👋
> 
> I think when the id of the stories change (like removing drafts) the tests themselves will need to be changed. I pushed up a commit that I think should tackle the new paths 🤞

Thanks so much @joshblack ! It is very interesting - I thought I did that step. I even documented it on the [depreciation component docs](https://github.com/primer/react/pull/2733/files#diff-1760a697b5e00b53e2aecf5aefbec00b6fd0a8fbee6a228fa3e74adfd33ed458R45) but apparently I failed to apply that step on my own PR lol Thanks a bunch!

**Comment by broccolinisoup** [comment]
Closing this in favor of https://github.com/primer/react/pull/3260

**Pull request closed without merging**
