### PR TITLE
Styled component bug cleanup

### PR DESCRIPTION
**Pull request by kendallgassner**
While working on Stylelint-a11y spike/exploration I noticed a couple of bugs in some styled blocks. This pr fixes those bugs -- they are pretty much nits.

### Screenshots

Please provide before/after screenshots for any visual changes

### Merge checklist

- [ ] Added/updated tests
- [ ] Added/updated documentation
- [ ] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Review by TylerJDev — APPROVED** [review]

**Review by joshblack — APPROVED** [review]
Thanks for this! 🥳

**Comment by joshblack** [comment]
One note for @mperrotti, it seems like the change here updates some styling for `Timeline` across light and dark high contrast themes. Specifically, it seems like the line above the item is not being displayed:

A GitHub timeline that shows two messages. There is a vertical bar that connects the status icons of these messages but the bar is missing in the second message in the timeline

**Review by mperrotti — APPROVED** [review]

**Comment by mperrotti** [comment]
@joshblack - these changes don't look like they should update how any of the styles are rendered. If the Timeline looks different on `main`, we should consider those to be visual regressions.

**Comment by joshblack** [comment]
Thanks @mperrotti! 

@kendallgassner should be good to go! Thanks again for this, I just added the `update snapshots` which should trigger updating the snapshots so VRT goes green ✅

**Pull request merged**
