### PR TITLE
Deprecate `MarkdownEditor`, `MarkdownViewer`, `InlineAutocomplete`, and related code

### PR DESCRIPTION
**Pull request by iansan5653**
Per https://github.com/primer/react/issues/3604, we will migrate the following draft/experimental APIs from `primer/react` to the internal GitHub codebase. Since drafts are not semvered we technically don't have to deprecate them, but I think it's still probably a good idea to follow a deprecation process rather than having them just disappear. So this PR deprecates the components, and then in v37 we can ultimately delete the code. This would be an aggressive timeline for other APIs, but again these are all drafts:

- `MarkdownEditor`
- `MardownViewer`
- `InlineAutocomplete`
- `hooks/useCombobox`
- `hooks/useDynamicTextareaHeight`
- `hooks/useIgnoreKeyboardActionsWhileComposing`
- `hooks/useSafeAsyncCallback`
- `hooks/useSyntheticChange`
- `hooks/useUnifiedFileSelect`, `useClickFileSelect`, `useDropFileSelect`, `usePasteFileSelect`

While some internal APIs will be migrated as well, I've focused on public APIs here.

Side note: I also moved `InlineAutocomplete` into `drafts` where it belongs. Not sure how it escaped :shrug:.

#### Changed

- Deprecated `MarkdownEditor`, `MardownViewer`, `InlineAutocomplete`, and related hooks

### Rollout strategy

- [ ] Patch release
- [x] Minor release
- [ ] Major release; if selected, include a written rollout or migration plan

### Merge checklist

- ~~[ ] Added/updated tests~~
- [x] Added/updated documentation
- [x] Added/updated previews (Storybook)
- [x] Changes are [SSR compatible](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#ssr-compatibility)
- ~~[ ] Tested in Chrome~~
- ~~[ ] Tested in Firefox~~
- ~~[ ] Tested in Safari~~
- ~~[ ] Tested in Edge~~
- ~~[ ] Integration tests pass at github/github ([Learn more about how to run integration tests](https://github.com/github/primer-engineering/blob/main/how-we-work/testing-primer-react-pr-at-dotcom.md))~~

Take a look at the [What we look for in reviews](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

**Comment by joshblack** [comment]
@iansan5653 just wanted to ask, is usage over in dotcom already migrated over to use the internal version of this component or would it be helpful to add linting to help folks move over to the new package?

**Comment by iansan5653** [comment]
> usage over in dotcom already migrated over to use the internal version of this component or would it be helpful to add linting to help folks move over to the new package?

Not yet. I haven't actually copied the code over to dotcom, but when I do so I will add linting accordingly. I have already added rules to lint specifically against importing `@primer/react/drafts/MarkdownEditor` since we have `CommentBox` in dotcom ([inflight](https://github.com/github/github/pull/302924))).

**Review by mperrotti — APPROVED** [review]
Assuming we don't want to move these to the `deprecated` package yet, this looks correct to me.

**Comment by iansan5653** [comment]
> Assuming we don't want to move these to the `deprecated` package yet, this looks correct to me.

Not sure what we would do here, since they are already in the `drafts` package. I'm open to moving them if you want.

**Pull request merged**
